author_string: Microsoft Core UEFI
copyright_string: Copyright (c) Microsoft Corporation.
description_string: QEMU SBSA DEBUG Platform Firmware
name: TEST.Mu.QemuSbsa.FW.DEBUG
project_url: https://microsoft.github.io/mu/
repository_type: git
repository_url: https://github.com/kuqin12/mu_tiano_platforms
server_url: https://nuget.pkg.github.com/kuqin12/index.json
tags_string: ''
