#
# This external dependency pulls MU_BASECORE for the Config feature package CI.
# This should not be pulled when consuming this package as a dependency.
#
{
  "scope": "global",
  "type": "git",
  "name": "FEATURE_CONFIG",
  "var_name": "FEATURE_CONFIG_PATH",
  "source": "https://github.com/kuqin12/mu_feature_config.git",
  "version": "bf65dbeec9015cbd9f0103ad668350a6729eca6c",
  "flags": ["set_build_var"]
}
