#
# This external dependency pulls mu_feature_config for platforms to consume.
#
{
  "scope": "global",
  "type": "git",
  "name": "FEATURE_CONFIG",
  "var_name": "FEATURE_CONFIG_PATH",
  "source": "https://github.com/microsoft/mu_feature_config.git",
  "version": "660a8e9def475cea45f927e780b446634b8e6db5",
  "flags": ["set_build_var"]
}
