## @file
# Azure Pipeline build file for building platforms with GCC.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/v2.4.0
  containers:
    - container: linux-gcc
      image: ghcr.io/tianocore/containers/fedora-37-test:54e5bd1

variables:
- group: tool-chain-ubuntu-gcc

jobs:
- template: Platform-Build-Job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: $(vm_image)
    pool_name: $(pool_name)
    container_image: linux-gcc
