## @file
# Azure Pipeline build file for building platforms with VS.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: kuqin12
      name: kuqin12/mu_devops
      ref: test_arm64

variables:
- group: tool-chain-windows-visual-studio-latest

jobs:
- template: Platform-Build-Job.yml
  parameters:
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
    pool_name: $(pool_name)
